### ISSUE TITLE
game standalone problem

### ISSUE THREAD

**Issue by ChrisRanger** [lil-lab/cerealbar#5]
Hi，I build game using Unity editor 2018.2.17f1 on Windows10，the WebGL is ok but the standalone(both windows and linux) exist problem like this.
![standlone](https://user-images.githubusercontent.com/37474653/118905730-e07fed80-b94e-11eb-894c-bb0f2c611c50.png)
![webgl](https://user-images.githubusercontent.com/37474653/118905752-ebd31900-b94e-11eb-806d-9368e1116f3e.png)
Obviously，the marked area is wrong in standalone game and I can’t control agent by keyboard.
Should I build standalone in MacOS？Could I interact with game (such as replay、evaluation reward、RL……etc) via other ways？I only found the code using standalone.
Wish your help, thx.

**Comment by alsuhr-c** [comment]
Area in the bottom left: yes, in the standalone this will look like this because it's providing maximum time, moves, and turns.

Not being able to control via keyboard: the standalone actually is not controllable via the keyboard. We intend for the standalone to be controllable only through socket messages, e.g., sent from python. I'm not sure what you are trying to do with the game, but for example if you just want to visualize the existing instruction examples in our dataset, [replay.py](https://github.com/lil-lab/cerealbar/blob/f59df0fbd4e99e95795174f6adb715604f1aecef/agent/simulation/replay.py) contains an example of this. 

1. First it creates a `ServerSocket` (here: https://github.com/lil-lab/cerealbar/blob/f59df0fbd4e99e95795174f6adb715604f1aecef/agent/simulation/replay.py#L80) which launches the standalone process.
2. Then for every game it creates a `UnityGame` (https://github.com/lil-lab/cerealbar/blob/f59df0fbd4e99e95795174f6adb715604f1aecef/agent/simulation/replay.py#L38) which keeps track of the state of the game board and communicates with the standalone.
3. An example of actually getting the players to move is in lines 60 and 63 of this file: `execute_leader_action` takes as input an action (MF, RR, RL, MB, or STOP) and executes it in the game. The agent's movements should appear in the standalone.

Does this make sense?

**Comment by ChrisRanger** [comment]
Got it! I haven't try to run replay.sh yet because I was wrong to think the standalone exist problem. Thank you so much bro!
